config/routes.rb
ShopifyApp::Application.routes.draw do
  resources :shopifyvariants

  resources :shopifylandingpages

  resources :shopifyproducts

  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root :to => 'home#index'

end

app/models/shopifyvariant.rb
class Shopifyvariant < ActiveRecord::Base
  attr_accessible :integer, :integer, :integer, :string, :string, :string, :string, :string, :string, :variantgrams, :variantid, :variantinvqty, :variantop1, :variantop2, :variantposition, :variantprice, :variantsku, :varianttitle
  belongs_to :shopifyproducts
end

app/controllers/shopifyvariants_controller.rb
class ShopifyvariantsController < ApplicationController
  # GET /shopifyvariants
  # GET /shopifyvariants.json
  def index
    @shopifyvariants = Shopifyvariant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shopifyvariants }
    end
  end

  # GET /shopifyvariants/1
  # GET /shopifyvariants/1.json
  def show
    @shopifyvariant = Shopifyvariant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopifyvariant }
    end
  end

  # GET /shopifyvariants/new
  # GET /shopifyvariants/new.json
  def new
    @shopifyvariant = Shopifyvariant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shopifyvariant }
    end
  end

  # GET /shopifyvariants/1/edit
  def edit
    @shopifyvariant = Shopifyvariant.find(params[:id])
  end

  # POST /shopifyvariants
  # POST /shopifyvariants.json
  def create
    @shopifyvariant = Shopifyvariant.new(params[:shopifyvariant])

    respond_to do |format|
      if @shopifyvariant.save
        format.html { redirect_to @shopifyvariant, notice: 'Shopifyvariant was successfully created.' }
        format.json { render json: @shopifyvariant, status: :created, location: @shopifyvariant }
      else
        format.html { render action: "new" }
        format.json { render json: @shopifyvariant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shopifyvariants/1
  # PUT /shopifyvariants/1.json
  def update
    @shopifyvariant = Shopifyvariant.find(params[:id])

    respond_to do |format|
      if @shopifyvariant.update_attributes(params[:shopifyvariant])
        format.html { redirect_to @shopifyvariant, notice: 'Shopifyvariant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shopifyvariant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopifyvariants/1
  # DELETE /shopifyvariants/1.json
  def destroy
    @shopifyvariant = Shopifyvariant.find(params[:id])
    @shopifyvariant.destroy

    respond_to do |format|
      format.html { redirect_to shopifyvariants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shopifyvariants_helper.rb
module ShopifyvariantsHelper
end

app/views/shopifyvariants/_form.html.erb
<%= form_for(@shopifyvariant) do |f| %>
  <% if @shopifyvariant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopifyvariant.errors.count, "error") %> prohibited this shopifyvariant from being saved:</h2>

      <ul>
      <% @shopifyvariant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :varianttitle %><br />
    <%= f.text_field :varianttitle %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :variantid %><br />
    <%= f.text_field :variantid %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :variantinvqty %><br />
    <%= f.text_field :variantinvqty %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :variantprice %><br />
    <%= f.text_field :variantprice %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="field">
    <%= f.label :variantop1 %><br />
    <%= f.text_field :variantop1 %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :variantop2 %><br />
    <%= f.text_field :variantop2 %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :variantgrams %><br />
    <%= f.text_field :variantgrams %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :variantposition %><br />
    <%= f.text_field :variantposition %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :variantsku %><br />
    <%= f.text_field :variantsku %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopifyvariants/edit.html.erb
<h1>Editing shopifyvariant</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopifyvariant %> |
<%= link_to 'Back', shopifyvariants_path %>

app/views/shopifyvariants/index.html.erb
<h1>Listing shopifyvariants</h1>

<table>
  <tr>
    <th>Varianttitle</th>
    <th>String</th>
    <th>Variantid</th>
    <th>Integer</th>
    <th>Variantinvqty</th>
    <th>Integer</th>
    <th>Variantprice</th>
    <th>Integer</th>
    <th>Variantop1</th>
    <th>String</th>
    <th>Variantop2</th>
    <th>String</th>
    <th>Variantgrams</th>
    <th>String</th>
    <th>Variantposition</th>
    <th>String</th>
    <th>Variantsku</th>
    <th>String</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shopifyvariants.each do |shopifyvariant| %>
  <tr>
    <td><%= shopifyvariant.varianttitle %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= shopifyvariant.variantid %></td>
    <td><%= shopifyvariant.integer %></td>
    <td><%= shopifyvariant.variantinvqty %></td>
    <td><%= shopifyvariant.integer %></td>
    <td><%= shopifyvariant.variantprice %></td>
    <td><%= shopifyvariant.integer %></td>
    <td><%= shopifyvariant.variantop1 %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= shopifyvariant.variantop2 %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= shopifyvariant.variantgrams %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= shopifyvariant.variantposition %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= shopifyvariant.variantsku %></td>
    <td><%= shopifyvariant.string %></td>
    <td><%= link_to 'Show', shopifyvariant %></td>
    <td><%= link_to 'Edit', edit_shopifyvariant_path(shopifyvariant) %></td>
    <td><%= link_to 'Destroy', shopifyvariant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shopifyvariant', new_shopifyvariant_path %>

app/views/shopifyvariants/new.html.erb
<h1>New shopifyvariant</h1>

<%= render 'form' %>

<%= link_to 'Back', shopifyvariants_path %>

app/views/shopifyvariants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Varianttitle:</b>
  <%= @shopifyvariant.varianttitle %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>

<p>
  <b>Variantid:</b>
  <%= @shopifyvariant.variantid %>
</p>

<p>
  <b>Integer:</b>
  <%= @shopifyvariant.integer %>
</p>

<p>
  <b>Variantinvqty:</b>
  <%= @shopifyvariant.variantinvqty %>
</p>

<p>
  <b>Integer:</b>
  <%= @shopifyvariant.integer %>
</p>

<p>
  <b>Variantprice:</b>
  <%= @shopifyvariant.variantprice %>
</p>

<p>
  <b>Integer:</b>
  <%= @shopifyvariant.integer %>
</p>

<p>
  <b>Variantop1:</b>
  <%= @shopifyvariant.variantop1 %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>

<p>
  <b>Variantop2:</b>
  <%= @shopifyvariant.variantop2 %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>

<p>
  <b>Variantgrams:</b>
  <%= @shopifyvariant.variantgrams %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>

<p>
  <b>Variantposition:</b>
  <%= @shopifyvariant.variantposition %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>

<p>
  <b>Variantsku:</b>
  <%= @shopifyvariant.variantsku %>
</p>

<p>
  <b>String:</b>
  <%= @shopifyvariant.string %>
</p>


<%= link_to 'Edit', edit_shopifyvariant_path(@shopifyvariant) %> |
<%= link_to 'Back', shopifyvariants_path %>