config/routes.rb
ShopifyApp::Application.routes.draw do
  resources :shopifyvariants

  resources :shopifylandingpages

  resources :shopifyproducts

  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root :to => 'home#index'

end

app/models/shopifylandingpage.rb
class Shopifylandingpage < ActiveRecord::Base
    has_many :shopifyproducts
attr_accessible :shopifylandingpage_id, :producttype, :integer, :producttitle, :producthandle, :productid, :producthtml, :productimage1, :productimage2, :productimage3, :producthtml, :setname  
 
end

app/controllers/shopifylandingpages_controller.rb
class ShopifylandingpagesController < ApplicationController
  # GET /shopifylandingpages
  # GET /shopifylandingpages.json
  def index
    @shopifylandingpages = Shopifylandingpage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shopifylandingpages }
    end
  end

  # GET /shopifylandingpages/1
  # GET /shopifylandingpages/1.json
  def show
    @shopifylandingpage = Shopifylandingpage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopifylandingpage }
    end
  end

  # GET /shopifylandingpages/new
  # GET /shopifylandingpages/new.json
  def new
    @shopifylandingpage = Shopifylandingpage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shopifylandingpage }
    end
  end

  # GET /shopifylandingpages/1/edit
  def edit
    @shopifylandingpage = Shopifylandingpage.find(params[:id])
  end

  # POST /shopifylandingpages
  # POST /shopifylandingpages.json
  def create
    @shopifylandingpage = Shopifylandingpage.new(params[:shopifylandingpage])

    respond_to do |format|
      if @shopifylandingpage.save
        format.html { redirect_to @shopifylandingpage, notice: 'Shopifylandingpage was successfully created.' }
        format.json { render json: @shopifylandingpage, status: :created, location: @shopifylandingpage }
      else
        format.html { render action: "new" }
        format.json { render json: @shopifylandingpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shopifylandingpages/1
  # PUT /shopifylandingpages/1.json
  def update
    @shopifylandingpage = Shopifylandingpage.find(params[:id])

    respond_to do |format|
      if @shopifylandingpage.update_attributes(params[:shopifylandingpage])
        format.html { redirect_to @shopifylandingpage, notice: 'Shopifylandingpage was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shopifylandingpage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopifylandingpages/1
  # DELETE /shopifylandingpages/1.json
  def destroy
    @shopifylandingpage = Shopifylandingpage.find(params[:id])
    @shopifylandingpage.destroy

    respond_to do |format|
      format.html { redirect_to shopifylandingpages_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shopifylandingpages_helper.rb
module ShopifylandingpagesHelper
end

app/views/shopifylandingpages/_form.html.erb
<%= form_for(@shopifylandingpage) do |f| %>
  <% if @shopifylandingpage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopifylandingpage.errors.count, "error") %> prohibited this shopifylandingpage from being saved:</h2>

      <ul>
      <% @shopifylandingpage.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producttype %><br />
    <%= f.text_field :producttype %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :producttitle %><br />
    <%= f.text_field :producttitle %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :producthandle %><br />
    <%= f.text_field :producthandle %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :productimage1 %><br />
    <%= f.text_field :productimage1 %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :productimage2 %><br />
    <%= f.text_field :productimage2 %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :productimage3 %><br />
    <%= f.text_field :productimage3 %>
  </div>
  <div class="field">
    <%= f.label :string %><br />
    <%= f.text_field :string %>
  </div>
  <div class="field">
    <%= f.label :productid %><br />
    <%= f.text_field :productid %>
  </div>
  <div class="field">
    <%= f.label :integer %><br />
    <%= f.text_field :integer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopifylandingpages/edit.html.erb
<h1>Editing shopifylandingpage</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopifylandingpage %> |
<%= link_to 'Back', shopifylandingpages_path %>

app/views/shopifylandingpages/index.html.erb
<h1>Listing shopifylandingpages</h1>

<table>
  <tr>
    <th>Producttype</th>
    <th>String</th>
    <th>Producttitle</th>
    <th>String</th>
    <th>Producthandle</th>
    <th>String</th>
    <th>Productimage1</th>
    <th>String</th>
    <th>Productimage2</th>
    <th>String</th>
    <th>Productimage3</th>
    <th>String</th>
    <th>Productid</th>
    <th>Integer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shopifylandingpages.each do |shopifylandingpage| %>
  <tr>
    <td><%= shopifylandingpage.producttype %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.producttitle %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.producthandle %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.productimage1 %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.productimage2 %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.productimage3 %></td>
    <td><%= shopifylandingpage.string %></td>
    <td><%= shopifylandingpage.productid %></td>
    <td><%= shopifylandingpage.integer %></td>
    <td><%= link_to 'Show', shopifylandingpage %></td>
    <td><%= link_to 'Edit', edit_shopifylandingpage_path(shopifylandingpage) %></td>
    <td><%= link_to 'Destroy', shopifylandingpage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shopifylandingpage', new_shopifylandingpage_path %>

app/views/shopifylandingpages/new.html.erb
<h1>New shopifylandingpage</h1>

<%= render 'form' %>

<%= link_to 'Back', shopifylandingpages_path %>

app/views/shopifylandingpages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producttype:</b>
  <%= @shopifylandingpage.producttype %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Producttitle:</b>
  <%= @shopifylandingpage.producttitle %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Producthandle:</b>
  <%= @shopifylandingpage.producthandle %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Productimage1:</b>
  <%= @shopifylandingpage.productimage1 %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Productimage2:</b>
  <%= @shopifylandingpage.productimage2 %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Productimage3:</b>
  <%= @shopifylandingpage.productimage3 %>
</p>

<p>
  <b>String:</b>
  <%= @shopifylandingpage.string %>
</p>

<p>
  <b>Productid:</b>
  <%= @shopifylandingpage.productid %>
</p>

<p>
  <b>Integer:</b>
  <%= @shopifylandingpage.integer %>
</p>


<%= link_to 'Edit', edit_shopifylandingpage_path(@shopifylandingpage) %> |
<%= link_to 'Back', shopifylandingpages_path %>