config/routes.rb
ShopifyApp::Application.routes.draw do
  resources :shopifyvariants

  resources :shopifylandingpages

  resources :shopifyproducts

  get 'welcome' => 'home#welcome'
  get 'design' => 'home#design'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    get 'auth/shopify/callback' => :show
    delete 'logout' => :destroy
  end

  root :to => 'home#index'

end

app/models/shopifyproduct.rb
class Shopifyproduct < ActiveRecord::Base

belongs_to :shopifylandingpage
has_many :shopifyvariants
attr_accessible :shopifylandingpage_id, :productid, :producttype, :producttitle, :producthandle, :imageurl
 
end

app/controllers/shopifyproducts_controller.rb
class ShopifyproductsController < ApplicationController
  # GET /shopifyproducts
  # GET /shopifyproducts.json
  def index
    @shopifyproducts = Shopifyproduct.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shopifyproducts }
    end
  end

  # GET /shopifyproducts/1
  # GET /shopifyproducts/1.json
  def show
    @shopifyproduct = Shopifyproduct.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shopifyproduct }
    end
  end

  # GET /shopifyproducts/new
  # GET /shopifyproducts/new.json
  def new
    @shopifyproduct = Shopifyproduct.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shopifyproduct }
    end
  end

  # GET /shopifyproducts/1/edit
  def edit
    @shopifyproduct = Shopifyproduct.find(params[:id])
  end

  # POST /shopifyproducts
  # POST /shopifyproducts.json
  def create
    @shopifyproduct = Shopifyproduct.new(params[:shopifyproduct])

    respond_to do |format|
      if @shopifyproduct.save
        format.html { redirect_to @shopifyproduct, notice: 'Shopifyproduct was successfully created.' }
        format.json { render json: @shopifyproduct, status: :created, location: @shopifyproduct }
      else
        format.html { render action: "new" }
        format.json { render json: @shopifyproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shopifyproducts/1
  # PUT /shopifyproducts/1.json
  def update
    @shopifyproduct = Shopifyproduct.find(params[:id])

    respond_to do |format|
      if @shopifyproduct.update_attributes(params[:shopifyproduct])
        format.html { redirect_to @shopifyproduct, notice: 'Shopifyproduct was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @shopifyproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopifyproducts/1
  # DELETE /shopifyproducts/1.json
  def destroy
    @shopifyproduct = Shopifyproduct.find(params[:id])
    @shopifyproduct.destroy

    respond_to do |format|
      format.html { redirect_to shopifyproducts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/shopifyproducts_helper.rb
module ShopifyproductsHelper
end

app/views/shopifyproducts/_form.html.erb
<%= form_for(@shopifyproduct) do |f| %>
  <% if @shopifyproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopifyproduct.errors.count, "error") %> prohibited this shopifyproduct from being saved:</h2>

      <ul>
      <% @shopifyproduct.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :producttitle %><br />
    <%= f.text_field :producttitle %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopifyproducts/edit.html.erb
<h1>Editing shopifyproduct</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopifyproduct %> |
<%= link_to 'Back', shopifyproducts_path %>

app/views/shopifyproducts/index.html.erb
<h1>Listing shopifyproducts</h1>

<table>
  <tr>
    <th>Producttitle</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @shopifyproducts.each do |shopifyproduct| %>
  <tr>
    <td><%= shopifyproduct.producttitle %></td>
    <td><%= link_to 'Show', shopifyproduct %></td>
    <td><%= link_to 'Edit', edit_shopifyproduct_path(shopifyproduct) %></td>
    <td><%= link_to 'Destroy', shopifyproduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Shopifyproduct', new_shopifyproduct_path %>

app/views/shopifyproducts/new.html.erb
<h1>New shopifyproduct</h1>

<%= render 'form' %>

<%= link_to 'Back', shopifyproducts_path %>

app/views/shopifyproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Producttitle:</b>
  <%= @shopifyproduct.producttitle %>
</p>


<%= link_to 'Edit', edit_shopifyproduct_path(@shopifyproduct) %> |
<%= link_to 'Back', shopifyproducts_path %>